#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
 
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /app
 
EXPOSE 80
 
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["ArquitecturaMercansoft/ArquitecturaMercansoft.csproj", "ArquitecturaMercansoft/"]
COPY ["Business/Business.csproj", "Business/"]
COPY ["DataAccess/DataAccess.csproj", "DataAccess/"]
COPY ["Transversal/Transversal.csproj", "Transversal/"]
RUN dotnet restore "ArquitecturaMercansoft/ArquitecturaMercansoft.csproj"
COPY . .
#COPY . ./
#RUN dotnet restore
#RUN dotnet publish -c Release -o out
WORKDIR "/src/ArquitecturaMercansoft"
RUN dotnet build "ArquitecturaMercansoft.csproj" -c Release -o /app/build
 
FROM build AS publish
RUN dotnet publish "ArquitecturaMercansoft.csproj" -c Release -o /app/publish
 
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ArquitecturaMercansoft.dll"]
 
#FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
#WORKDIR /app
#COPY --from=base /app/Customer.ArquitecturaMercansoft/out .
#ENTRYPOINT ["dotnet", "ArquitecturaMercansoft.dll"]